import { SectionHeading } from '../components/common/SectionHeading'
import { Seo } from '../components/common/Seo'
import { Navbar } from '../components/layout/Navbar'
import { ProjectCard } from '../components/projects/ProjectCard'
import { projects } from '../data/projects'
import { skillGroups } from '../data/skills'

const externalLinks = [
  { label: 'GitHub', href: 'https://github.com/SnayderC' },
  { label: 'LinkedIn', href: 'https://linkedin.com/in/SnayderCJ' },
]

export function HomePage() {
  return <><Seo title="Snayder Cedeño | Junior Full Stack Developer" /><a href="#main-content" className="skip-link">Saltar al contenido</a><Navbar /><main id="main-content">
    <section id="inicio" className="border-b border-[var(--border)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:py-28 lg:grid-cols-[1.15fr_.85fr] lg:px-8">
      <div><p className="inline-flex items-center gap-2 rounded-full border border-[color:rgb(52_211_153_/_0.35)] bg-[color:rgb(52_211_153_/_0.08)] px-3 py-1.5 font-mono text-xs text-[var(--accent)]"><span className="h-2 w-2 rounded-full bg-[var(--accent)]" />Disponible para oportunidades Junior</p>
        <h1 className="mt-7 max-w-3xl text-4xl font-bold tracking-[-0.04em] text-[var(--text-primary)] sm:text-5xl lg:text-6xl">Construyo aplicaciones web completas, desde la interfaz hasta la API.</h1>
        <p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--text-secondary)]">Soy Snayder Cedeño, estudiante de Ingeniería de Software y Desarrollador Full Stack Junior. Desarrollo soluciones con Python, Django REST Framework, React, PostgreSQL y Docker.</p>
        <div className="mt-8 flex flex-wrap gap-3"><a href="#proyectos" className="rounded-lg bg-[var(--primary)] px-5 py-3 font-semibold text-[#08111e] transition hover:bg-[var(--primary-hover)]">Ver mis proyectos</a><a href="/cv/Snayder-Cedeno-CV.pdf" download className="rounded-lg border border-[var(--border)] px-5 py-3 font-semibold text-[var(--text-primary)] transition hover:border-[var(--primary)]">Descargar CV</a></div>
        <ul className="mt-10 grid gap-3 text-sm text-[var(--text-secondary)] sm:grid-cols-3"><li>Milagro, Ecuador</li><li>Disponible para trabajo remoto</li><li>Español nativo · Inglés intermedio</li></ul>
      </div>
      <aside className="self-center rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-2xl shadow-black/20"><div className="flex items-center gap-2 border-b border-[var(--border)] pb-4"><span className="h-2.5 w-2.5 rounded-full bg-rose-400" /><span className="h-2.5 w-2.5 rounded-full bg-[var(--warning)]" /><span className="h-2.5 w-2.5 rounded-full bg-[var(--accent)]" /><span className="ml-2 font-mono text-xs text-[var(--text-muted)]">developer.ts</span></div><pre className="mt-5 overflow-x-auto font-mono text-sm leading-7 text-[var(--text-secondary)]"><code><span className="text-[var(--primary)]">const</span> developer = {'{'}{`\n`}  name: <span className="text-[var(--accent)]">"Snayder Cedeño"</span>,{`\n`}  role: <span className="text-[var(--accent)]">"Junior Full Stack Developer"</span>,{`\n`}  backend: [<span className="text-[var(--accent)]">"Python", "Django REST"</span>],{`\n`}  frontend: [<span className="text-[var(--accent)]">"React", "TypeScript"</span>],{`\n`}  database: <span className="text-[var(--accent)]">"PostgreSQL"</span>,{`\n`}  available: <span className="text-[var(--warning)]">true</span>,{`\n`}{'}'};</code></pre></aside>
    </div></section>
    <section id="sobre-mi" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><SectionHeading eyebrow="01 — SOBRE MÍ" title="Construyendo productos web con una base sólida." description="Soy estudiante de Ingeniería de Software en la Universidad Estatal de Milagro, con interés profesional en desarrollo Full Stack y Backend. He desarrollado aplicaciones con autenticación, APIs REST, bases de datos relacionales, lógica empresarial, inteligencia artificial y despliegue en la nube." /><div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">{[['03', 'proyectos destacados'], ['Full Stack', 'y Backend'], ['2026', 'graduación prevista']].map(([value, label]) => <div key={label} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><strong className="text-xl text-[var(--text-primary)]">{value}</strong><p className="mt-1 text-sm text-[var(--text-secondary)]">{label}</p></div>)}</div></div></section>
    <section id="proyectos" className="border-y border-[var(--border)] bg-[color:rgb(15_23_42_/_0.45)]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionHeading eyebrow="02 — PROYECTOS" title="Trabajo seleccionado" description="Proyectos que reflejan mi experiencia práctica en desarrollo Full Stack, Backend y colaboración con Git." /><div className="mt-10 grid gap-5 lg:grid-cols-2"><ProjectCard project={projects[0]} prominent />{projects.slice(1).map((project) => <ProjectCard key={project.id} project={project} />)}</div></div></section>
    <section id="tecnologias" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionHeading eyebrow="03 — TECNOLOGÍAS" title="Herramientas que uso para construir." /><div className="mt-10 grid gap-5 md:grid-cols-3">{skillGroups.map((group) => <section key={group.title} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><h3 className="font-mono text-sm text-[var(--primary)]">{group.title}</h3><ul className="mt-5 flex flex-wrap gap-2">{group.skills.map((skill) => <li key={skill} className="rounded-md bg-[var(--surface-elevated)] px-2.5 py-1.5 text-sm text-[var(--text-secondary)]">{skill}</li>)}</ul></section>)}</div></section>
    <section id="formacion" className="border-y border-[var(--border)] bg-[color:rgb(15_23_42_/_0.45)]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionHeading eyebrow="04 — FORMACIÓN" title="Aprendizaje académico y práctica aplicada." /><div className="mt-10 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><p className="font-mono text-sm text-[var(--primary)]">EDUCACIÓN</p><h3 className="mt-4 text-xl font-bold">Ingeniería de Software</h3><p className="mt-2 text-[var(--text-secondary)]">Universidad Estatal de Milagro — UNEMI</p><p className="mt-3 text-sm text-[var(--text-muted)]">Marzo de 2022 – Actualidad · Graduación prevista: 2026</p></article><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><p className="font-mono text-sm text-[var(--primary)]">EXPERIENCIA PRÁCTICA</p><h3 className="mt-4 text-xl font-bold">Proyectos académicos e independientes</h3><p className="mt-2 text-[var(--text-secondary)]">Desarrollo Full Stack con React, Django REST Framework, APIs REST, bases de datos relacionales, autenticación y despliegue cloud.</p><p className="mt-3 text-sm text-[var(--text-muted)]">2024 – Actualidad</p></article></div></div></section>
    <section id="contacto" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-8 sm:p-12"><SectionHeading eyebrow="05 — CONTACTO" title="¿Construimos algo juntos?" description="Estoy disponible para oportunidades como Desarrollador Full Stack Junior, Backend Python Junior, Desarrollador Web o practicante de Ingeniería de Software." /><div className="mt-8 flex flex-wrap gap-3"><a href="mailto:cedenosnyder@gmail.com" className="rounded-lg bg-[var(--primary)] px-5 py-3 font-semibold text-[#08111e] hover:bg-[var(--primary-hover)]">Enviar correo</a>{externalLinks.map((link) => <a key={link.label} href={link.href} target="_blank" rel="noreferrer" className="rounded-lg border border-[var(--border)] px-5 py-3 font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-elevated)]">{link.label} ↗</a>)}<a href="/cv/Snayder-Cedeno-CV.pdf" download className="rounded-lg border border-[var(--border)] px-5 py-3 font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-elevated)]">Descargar CV</a></div><p className="mt-8 text-sm text-[var(--text-muted)]">cedenosnyder@gmail.com · Milagro, Guayas, Ecuador · Disponible para trabajo remoto</p></div></section>
  </main><footer className="border-t border-[var(--border)] px-5 py-7 text-center text-sm text-[var(--text-muted)]">© {new Date().getFullYear()} Snayder Cedeño. Construido con React, TypeScript y Tailwind CSS.</footer></>
}
